name: Security Analysis

on:
  push:
    branches:
      - main
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Solc with Snap
      run: |
        # Install snap if not already installed
        sudo apt update
        sudo apt install -y snapd
        # Install solc using snap
        sudo snap install solc --classic
        # Verify solc installation
        solc --version

    - name: Install Python and Slither
      run: |
        # Install Python and pip
        sudo apt install -y python3 python3-pip
        # Upgrade pip
        pip install --upgrade pip
        # Install Slither Analyzer
        pip install slither-analyzer

    - name: Run Slither Analysis
      run: |
        # Run Slither on the smart contracts
        slither .
