name: Security Analysis

on:
  push:
    branches:
      - main
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 for stability

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Specific Solc Version
      run: |
        # Update the system and install snapd if not already installed
        sudo apt update
        sudo apt install -y snapd
        # Install the Solidity compiler (specific version for compatibility)
        sudo snap install solc --channel=0.8/stable --classic
        # Verify the installed solc version
        solc --version

    - name: Install Python and Slither
      run: |
        # Install Python and pip
        sudo apt install -y python3 python3-pip
        # Upgrade pip to the latest version
        pip install --upgrade pip
        # Install Slither Analyzer
        pip install slither-analyzer

    - name: Run Slither Analysis
      run: |
        # Run Slither on the smart contracts
        slither .
