name: Security Analysis

on:
  push:
    branches:
      - main
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 for stability

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Specific Solc Version
      run: |
        # Add Ethereum PPA to access solc versions
        sudo add-apt-repository -y ppa:ethereum/ethereum
        sudo apt update
        # Install a specific version of solc (replace VERSION with the required version, e.g., 0.8.20)
        sudo apt install -y solc=0.8.20-1ubuntu1~20.04
        # Verify installed solc version
        solc --version

    - name: Install Python and Slither
      run: |
        # Install Python and pip
        sudo apt install -y python3 python3-pip
        # Upgrade pip
        pip install --upgrade pip
        # Install Slither Analyzer
        pip install slither-analyzer

    - name: Run Slither Analysis
      run: |
        # Run Slither on the smart contracts
        slither .
