name: Security Analysis

on:
  push:
    branches:
      - main
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 for stability

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        # Install snap and solc via snap
        sudo apt update
        sudo apt install -y snapd
        sudo snap install solc --classic
        # Install Python and pip
        sudo apt install -y python3 python3-pip
        pip install --upgrade pip
        pip install slither-analyzer

    - name: Run Slither Analysis
      run: |
        # Run Slither on the smart contracts
        slither .
